export const COMPONENTS = {
  TEXT_FIELD: 'TEXT_FIELD',
  SELECT_BOX: 'SELECT_BOX',
  CHECKBOX: 'CHECKBOX',
  RADIO: 'RADIO',
  AUTOCOMPLETE: 'AUTOCOMPLETE',
  DATEPICKER: 'DATEPICKER',
  TEXT_AREA: 'TEXT_AREA',
  MULTI_SELECT_BOX: 'MULTI_SELECT_BOX',
  BUTTON: 'BUTTON',
  LINK: 'LINK',
  NONE: 'NONE',
  TYPOGRAPHY: 'TYPOGRAPHY',
  ICON: 'ICON'
};

export const API_RESPONSE_CODES = {
  SUCCESS: 200,
  SUCCESS_CREATE: 201,
  SUCCESS_NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORISED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  PAYLOAD_ERROR: 502
};
