export const PROJECTDETAILS = "PROJECTDETAILS";
export const JOBDETAILS = "JOBDETAILS";
export const JOBFILTER = "JOBFILTER";
export const CLIENTDETAILS = "CLIENTDETAILS";
export const PROJECTFILTER = "PROJECTFILTER";
export const CLIENTFILTER = "CLIENTFILTER";
export const REFRESH = "REFRESH";
