export const userRecords = {
  data: [
    {
      id: 100,
      empid: "Emp100",
      firstName: "Deepali",
      lastName: "Bhandare",
      emailId: "deepalibhandare@gmail.com",
      phoneNumber: 1234567890,
      password: null,
    },
    {
      id: 200,
      empid: "Emp200",
      firstName: "Prathmesh",
      lastName: "Jadhav",
      emailId: "prathmeshjadhav@gmail.com",
      phoneNumber: 1234567890,
      password: null,
    },
    {
      id: 300,
      empid: "Emp300",
      firstName: "Sanchet",
      lastName: "",
      emailId: "sanchet@gmail.com",
      phoneNumber: 1234567890,
      password: null,
    },
    {
      id: 400,
      empid: "Emp400",
      firstName: "Meenal",
      lastName: "Phatak",
      emailId: "meenalphatak@gmail.com",
      phoneNumber: 1234567890,
      password: null,
    },
  ],
};
