export const clientRecords = [
  {
    id: 11,
    shortName: "test",
    firstName: "test",
    lastName: "test",
    billingId: 100,
    billing: "HJR",
    currencyId: 100,
    currency: "USD",
    clientStatusId: 100,
    clientStatus: null,
    clientcontactdetailsdto: [
      {
        id: 7,
        emailId: "deepalibhandare1996@gmail.com",
        phoneNumber: "123456789012",
        address: "nigdi",
        mobile: 1234567890,
        fax: 1234123457,
        isPrimary: true,
        clientId: 11,
      },
    ],
  },
  {
    id: 12,
    shortName: "abc",
    firstName: "deepali",
    lastName: "bhandare",
    billingId: 100,
    billing: null,
    currencyId: 100,
    currency: null,
    clientStatusId: 100,
    clientStatus: null,
    clientcontactdetailsdto: [
      {
        id: 8,
        emailId: "deepalibhandare1996@gmail.com",
        phoneNumber: "123456789123",
        address: "nigdi",
        mobile: 1234567891,
        fax: 1234567891,
        isPrimary: true,
        clientId: 12,
      },
    ],
  },
  {
    id: 14,
    shortName: "Deepali",
    firstName: "Deepa",
    lastName: "Bhndare",
    billingId: 100,
    billing: null,
    currencyId: 100,
    currency: null,
    clientStatusId: 100,
    clientStatus: null,
    clientcontactdetailsdto: [
      {
        id: 9,
        emailId: "deepalibhandare1996@gmail.com",
        phoneNumber: "123456789123",
        address: "string",
        mobile: 1234567890,
        fax: 1234567890,
        isPrimary: true,
        clientId: 14,
      },
    ],
  },
];